### ISSUE TITLE
`goagen swagger` references httprouter but does not import it

### ISSUE THREAD

**Issue by interlock** [raphael/goa#108]
Referenced here: https://github.com/raphael/goa/blob/master/goagen/gen_swagger/generator.go#L94

**Comment by on99** [comment]
It's imported by `goimports` by `gg.FormatCode()`  https://github.com/raphael/goa/blob/master/goagen/gen_swagger/generator.go#L81

**Comment by on99** [comment]
By now, `httprouter` is a missing dependency but my pull request #106 has fixed this issue.

**Comment by raphael** [comment]
Thanks for the PR @on99 !
I believe we should still add the missing dependency explicitly here: https://github.com/raphael/goa/blob/master/goagen/gen_swagger/generator.go#L72 . Good catch @interlock !

**Comment by on99** [comment]
@raphael  yeh we can do it explicitly or just leave it to `goimports`. As long as `make` successfully, people may not have such kind of problem XD.

**Comment by raphael** [comment]
Yeah goimport will fix it but sometimes it doesn't get it right (e.g. finds another package with the same name). I find it's safer to be explicit.

**Comment by on99** [comment]
@raphael  Right. I agree. So it seems like `github.com/rightscale/rsc` is import mistakenly which is removed by pull request #110  XD. Maybe also remove  it from `Makefile`.

**Comment by raphael** [comment]
Ah yes I missed that - this package wasn't supposed to be imported. That's the drawback of `goimport` automagically fixing things on save ;)
