### ISSUE TITLE
DSL for map[string]interface{} ?

### ISSUE THREAD

**Issue by nizsheanez** [raphael/goa#109]
How to describe design for map[string]interface{} ?

**Comment by raphael** [comment]
That's on the list :) For now a workaround is to use `String` and make the call to `json.Unmarshal` yourself.

**Comment by nizsheanez** [comment]
Do you have some "list"/Roadmap?

**Comment by arangamani** [comment]
:+1:

**Comment by raphael** [comment]
There's a "roadmap" in the [wiki](https://github.com/raphael/goa/wiki/goa-Roadmap) but it's far from complete (this item is missing for example).

**Comment by raphael** [comment]
The PR above adds the type `Any` to the DSL. This type maps to `interface{}` in Go so that doing for example:
```go
var Payload = Type("payload", func() {
    Attribute("foo", HashOf(String, Any))
})
```
will result in the Go struct:
```go
type Payload struct {
    Foo map[string]interface{}
}
```

**Comment by nizsheanez** [comment]
cool, look similar to Protobuf 3 https://developers.google.com/protocol-buffers/docs/proto3#any
