### ISSUE TITLE
question: DSL: Require nested attribute in payload

### ISSUE THREAD

**Issue by wongak** [raphael/goa#123]
Hi,

how would one mark a nested attribute as required in a payload?

For example:

    var DataType = Type("DataType", func() {
        Attribute("id", Integer)
    })

    var TestPayload = Type("TestPayload", func() {
        Attribute("test", String)
        Attribute("data", DataType)
    })

    ....

    Payload(TestPayload, func() {
        Required("test")
    })

How would one mark the test ```DataType``` ```id``` attribute as required in the Payload?

**Comment by raphael** [comment]
You would mark is as required in the definition of the embedded type itself:
```
var DataType = Type("DataType", func() {
    Attribute("id", Integer)
    Required("id")
})
```

**Comment by raphael** [comment]
Closing for now, reopen if the above does not work for you.
