### ISSUE TITLE
`Unmarshal(Marshal(userType))` fails with []string field

### ISSUE THREAD

**Issue by jim-slattery-rs** [raphael/goa#137]
Trying to validate an object by Marshalling it and then Unmarshalling it, but getting this error:
```go
{
   "id":    3,
   "title": "invalid attribute type",
   "msg":   "type of load.Database.Global.ReadHosts must be array but got value []string{\"localhost\"}"
}
```

There seems to be an asymmetry in the generated code with handling a []string field:
- MarshalConfig() builds a `[]string`: https://github.com/rightscale/acl/blob/76ac08c2a53e949bb64b9262251a4d44680012d3/app/user_types.go#L73
- but UnmarshalConfig() expects an `[]interface`: https://github.com/rightscale/acl/blob/76ac08c2a53e949bb64b9262251a4d44680012d3/app/user_types.go#L141

Perhaps UnmarshalConfig() could handle both `[]interface` or `[]string`?

**Comment by raphael** [comment]
Hello Jim, you are correct that MarshalX and UnmarshalX are not symmetric operations. The idea is that the "MarshalX" methods will produce a data structure that can be encoded into JSON. Deserializing that representation and  calling "UnmarshalX" on the resulting raw "interface{}" will then produce back the same generated data structure.

It seems that you are doing that simply for validation? goagen currently generates `Validate` methods for media types and not user types. There is no good reason for this behavior and your use case shows that it would also be valuable for goagen to produce `Validate` methods for user types. I'll add these. Would that solve your use case?

**Comment by jim-slattery-rs** [comment]
Thanks Raphael, generating `Validate` methods for user types would solve my use case :)

**Comment by raphael** [comment]
Cool, closing this issue then.
