### ISSUE TITLE
Code generation error when using DSL Minimum(0)

### ISSUE THREAD

**Issue by noblehng** [raphael/goa#178]
The generated validation code for `Minimum(0)` will be something like:
```
if v > <no value> {
...
}
```
which is invalid.

The template for generating this is https://github.com/raphael/goa/blob/master/goagen/codegen/validation.go#L242. It use the value of the key `min` of the map `data` to determine whether the template is dealing with `Minimum()` or `Maximum()`.

From the document of `text/template`, `{{if pipeline}}` is checking against the empty value of `pipeline`, where the empty value is defined as:
> The empty values are false, 0, any nil pointer or interface value, and any array, slice, map, or string of length zero.

So for `Minimum(0)`, the template will actually think it is dealing with `Maximum()`, but the corresponding key `max` is missing from `data`, thus the generated text will be `> <no value>`.

I think `MinLength()` also has this problem, but no one will use `MinLength(0)`, so it's fine.

One solution for this, I think, would be to abuse the `data` map to store the actual validation type in it, and check against that in the template.

**Comment by raphael** [comment]
Ah nice catch! thank you, I'll fix it. I was aware of the template behavior but missed that case...

**Comment by raphael** [comment]
Thank you this is now fixed.
