### ISSUE TITLE
Trying to use Teaser example and it fails.

### ISSUE THREAD

**Issue by ChrisPRobinson** [raphael/goa#191]
This is likely a simple noob question. I was trying to use goa. As an initial example I was trying the teaser app on the main page of the repo. I executed the exact steps specified and I get the following error. 

panic: template: main:13: function "targetPkg" not defined

goroutine 1 [running]:
github.com/raphael/goa/goagen/codegen.(*SourceFile).ExecuteTemplate(0xc208152260, 0x4fdf20, 0x4, 0x60c4b0, 0x453, 0x0, 0x49ae00, 0xc2080c04d0, 0x0, 0x0)
	/Users/ChrisRobinson/go2/src/github.com/raphael/goa/goagen/codegen/workspace.go:263 +0x14c
github.com/raphael/goa/goagen/gen_main.func·005(0xc2080c04d0, 0x0, 0x0)
	/Users/ChrisRobinson/go2/src/github.com/raphael/goa/goagen/gen_main/generator.go:146 +0x471
github.com/raphael/goa/design.(*APIDefinition).IterateResources(0xc2080ebef0, 0xc20814fe30, 0x0, 0x0)
	/Users/ChrisRobinson/go2/src/github.com/raphael/goa/design/api.go:355 +0x267
github.com/raphael/goa/goagen/gen_main.(*Generator).Generate(0xc20810eb00, 0xc2080ebef0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/ChrisRobinson/go2/src/github.com/raphael/goa/goagen/gen_main/generator.go:155 +0x15e6
github.com/raphael/goa/goagen/gen_main.Generate(0xc2080ebef0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/ChrisRobinson/go2/src/github.com/raphael/goa/goagen/gen_main/generator.go:31 +0xa7
main.main()
	/var/folders/wq/hw1k0rbs56d7_lp7ln6v30j00000gn/T/goagen068784337/src/design/main.go:26 +0x5b

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 26 [chan receive]:
github.com/raphael/goa/goagen/utils.Catch(0x7a6c60, 0x6, 0x6, 0xc2080f1750)
	/Users/ChrisRobinson/go2/src/github.com/raphael/goa/goagen/utils/signal.go:15 +0xb1
created by github.com/raphael/goa/goagen/gen_main.(*Generator).Generate
	/Users/ChrisRobinson/go2/src/github.com/raphael/goa/goagen/gen_main/generator.go:63 +0x149

goroutine 29 [chan send]:
text/template/parse.lexRightDelim(0xc208114200, 0x5fb5b8)
	/usr/local/go/src/text/template/parse/lex.go:263 +0xb7
text/template/parse.(*lexer).run(0xc208114200)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

I'm running this on go 1.4, any ideas why this failure is occurring? I was trying to track it down. This failure is consistent for me, I tried in two different separate go path's that I had. Same issue. Am I missing a setting or was there a change that requires a change in the dsl to get this to work?

**Comment by raphael** [comment]
Woops, so much for teasing... I had a copy/paste error in a recent large refactor. It is now [fixed](https://github.com/raphael/goa/commit/54be64110543a860564edfd8f58fae49c8b9d84f) and I'll be adding tests shortly to cover this case. Thanks for reporting!

**Comment by ChrisPRobinson** [comment]
@raphael Thanks, I pulled down the latest and as expected it now works
