### ISSUE TITLE
HTTP response is Golang specific

### ISSUE THREAD

**Issue by jim-slattery-rs** [raphael/goa#50]
Tiny issue with a confusing error message.. When POSTing no data to an action that has required parameters, I get this 400 Bad Request response:
```json
[
    {
        "kind": 3, 
        "msg": "type of payload must be map[string]interface{} but got value <nil>", 
        "title": "invalid attribute type"
    }
]
```
The `msg` was a little confusing since it talks in Golang terms: `map[string]interface{}`. It really just wants me to submit some valid JSON, like at least `{}`.

**Comment by raphael** [comment]
Thanks @on99, closing this.
