### ISSUE TITLE
Slack and travis integration

### ISSUE THREAD

**Issue by on99** [raphael/goa#88]
* Make a [slackin](https://github.com/rauchg/slackin) so people can join slack without invitation
* Setup travis integration in slack

**Comment by raphael** [comment]
Thanks, these are good suggestions but the slack channel is graciously hosted by gopher academy (see https://blog.gopheracademy.com/gophers-slack-community/) which provides a nice safe environment. My invite request was replied to pretty much immediately so it doesn't seem like this should be an issue.

**Comment by on99** [comment]
Oh I mistakenly think it's your slack channel. Why not setup one on your own for goa development discussion, like [go-swagger](https://github.com/go-swagger/go-swagger)

**Comment by raphael** [comment]
Yeah that might make sense down the line. For now though there just doesn't seem to be enough activity to warrant two different slack channels.
