### ISSUE TITLE
Missing dependency packages

### ISSUE THREAD

**Issue by on99** [raphael/goa#98]
There are several dependencies missing in makefile so make cannot pass, fix it by 

Add missing packages to makefile

or

`vendor` `godep`

**Comment by raphael** [comment]
There's a `glide.yaml` file in the repo too. I've had mixed results with it (not many tools are aware of the vendor experiment yet). In particular I haven't been able to make Travis use it successfully.

**Comment by on99** [comment]
Yeh I agree. The issue is a bit more complicated than in other framework.

Let me fix fresh environment cannot run `make` successfully by adding those missing packages to `Makefile` first though we need a tool automating it. XD

**Comment by raphael** [comment]
Sounds like a good plan, thanks!

**Comment by bketelsen** [comment]
I heartily recommend `gb` for repeatable builds.
